const KEY="habitly-v3";
const defaults=[{id:1,name:"Move for 30 minutes",color:"mint",streak:4,done:false},{id:2,name:"Read 10 pages",color:"violet",streak:7,done:false},{id:3,name:"Drink 2L of water",color:"blue",streak:3,done:false}];
let habits=JSON.parse(localStorage.getItem(KEY)||"null")||defaults;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem(KEY,JSON.stringify(habits))}
function render(){const box=$("#habits");if(!box)return;box.innerHTML="";habits.forEach(h=>{const el=document.createElement("article");el.className="habit card";el.innerHTML='<div class="habitInfo"><i class="habitDot '+h.color+'"></i><div><h3 class="'+(h.done?"doneText":"")+'">'+h.name+'</h3><small>🔥 '+h.streak+' day streak</small></div></div><button class="delete" data-delete="'+h.id+'">×</button><button class="check '+(h.done?"done":"")+'" data-toggle="'+h.id+'">'+(h.done?"✓":"")+'</button>';box.appendChild(el)});const done=habits.filter(h=>h.done).length,total=habits.length,pct=total?Math.round(done/total*100):0;if($("#rate"))$("#rate").textContent=pct+"%";if($("#count"))$("#count").textContent=done+" of "+total+" complete";if($("#statToday"))$("#statToday").textContent=pct+"%";if($("#statHabits"))$("#statHabits").textContent=total;if($("#statStreak"))$("#statStreak").textContent=total?Math.max(...habits.map(h=>h.streak)):0;if($("#empty"))$("#empty").classList.toggle("hidden",total!==0);box.classList.toggle("hidden",total===0)}
function theme(dark){document.body.classList.toggle("dark",dark);localStorage.setItem("habitly-theme",dark?"dark":"light");if($("#themeBtn"))$("#themeBtn").textContent=dark?"☀":"☾";if($("#themeLabel"))$("#themeLabel").textContent=dark?"Dark theme":"Light theme"}
function openModal(){$("#modal").classList.remove("hidden");$("#habitName").focus()}
function closeModal(){$("#modal").classList.add("hidden");$("#habitForm").reset()}
function show(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".navBtn").forEach(x=>x.classList.remove("active"));const target=$("#"+v+"View");if(target)target.classList.add("active");const nav=document.querySelector('[data-view="'+v+'"]');if(nav)nav.classList.add("active")}
document.addEventListener("click",e=>{const t=e.target.closest("[data-toggle]");if(t){const h=habits.find(x=>String(x.id)===t.dataset.toggle);if(h){h.done=!h.done;h.streak=Math.max(0,h.streak+(h.done?1:-1));save();render()}return}const d=e.target.closest("[data-delete]");if(d){habits=habits.filter(x=>String(x.id)!==d.dataset.delete);save();render();return}const n=e.target.closest("[data-view]");if(n){show(n.dataset.view);return}});
$("#addBtn").onclick=openModal;$("#emptyAdd").onclick=openModal;$("#closeBtn").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};$("#habitForm").onsubmit=e=>{e.preventDefault();const name=$("#habitName").value.trim();if(!name)return;habits.push({id:Date.now(),name:name,color:$("#habitColor").value,streak:0,done:false});save();render();closeModal()};$("#themeBtn").onclick=()=>theme(!document.body.classList.contains("dark"));$("#settingsTheme").onclick=()=>theme(!document.body.classList.contains("dark"));$("#resetBtn").onclick=()=>{habits=defaults.map(h=>({...h}));save();render()};$("#homeBtn").onclick=e=>{e.preventDefault();show("today")};$("#date").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});theme(localStorage.getItem("habitly-theme")==="dark");render();